[platformio]
default_envs = esp32dev
test_dir = tests

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags = -std=gnu++17
lib_deps =
    dimag0g/PPM-reader @ ^1.0.0

[env:native]
platform = native
build_flags =
    -std=c++17
    -D NATIVE_BUILD
    -I include
build_src_filter = -<*> +<core/*>
lib_deps =
    doctest
lib_compat_mode = off
